import type { Employee, Contract, Payrun } from './types';

export const initialEmployees: Employee[] = [
  {
    id: 'EMP-001',
    name: 'John Doe',
    email: 'john.doe@company.com',
    department: 'Engineering',
    position: 'Senior Backend Engineer',
    status: 'ACTIVE',
    avatarInitials: 'JD',
    joinDate: '2023-03-15',
    activeContractId: 'CON-001',
    wage: 6500,
    schedule: 'Standard 40h',
    bankAccount: '•••• 4921',
    attendanceRate: 98,
    leaveBalance: 14,
  },
  {
    id: 'EMP-002',
    name: 'Maya Lin',
    email: 'maya.lin@company.com',
    department: 'Product',
    position: 'Lead Product Manager',
    status: 'ACTIVE',
    avatarInitials: 'ML',
    joinDate: '2022-08-01',
    activeContractId: 'CON-002',
    wage: 7200,
    schedule: 'Standard 40h',
    bankAccount: '•••• 8832',
    attendanceRate: 95,
    leaveBalance: 8,
  },
  {
    id: 'EMP-003',
    name: 'Alex Rivera',
    email: 'alex.rivera@company.com',
    department: 'Finance',
    position: 'Senior Payroll Specialist',
    status: 'ACTIVE',
    avatarInitials: 'AR',
    joinDate: '2024-01-10',
    activeContractId: 'CON-003',
    wage: 5200,
    schedule: 'Standard 40h',
    bankAccount: '•••• 1209',
    attendanceRate: 100,
    leaveBalance: 18,
  },
  {
    id: 'EMP-004',
    name: 'Elena Rostova',
    email: 'elena.r@company.com',
    department: 'Human Resources',
    position: 'HR Director',
    status: 'ACTIVE',
    avatarInitials: 'ER',
    joinDate: '2021-06-15',
    activeContractId: 'CON-004',
    wage: 8000,
    schedule: 'Standard 40h',
    bankAccount: '•••• 3490',
    attendanceRate: 96,
    leaveBalance: 21,
  },
  {
    id: 'EMP-005',
    name: 'David Kim',
    email: 'david.kim@company.com',
    department: 'Engineering',
    position: 'DevOps Architect',
    status: 'PROBATION',
    avatarInitials: 'DK',
    joinDate: '2026-07-01',
    activeContractId: 'CON-005',
    wage: 6800,
    schedule: 'Flexible 40h',
    bankAccount: '•••• 7712',
    attendanceRate: 92,
    leaveBalance: 5,
  },
  {
    id: 'EMP-006',
    name: 'Sarah Connor',
    email: 'sarah.c@company.com',
    department: 'Operations',
    position: 'Site Reliability Lead',
    status: 'ACTIVE',
    avatarInitials: 'SC',
    joinDate: '2023-11-20',
    activeContractId: 'CON-006',
    wage: 6300,
    schedule: 'Standard 40h',
    bankAccount: '•••• 6620',
    attendanceRate: 97,
    leaveBalance: 12,
  },
];

export const initialContracts: Contract[] = [
  { id: 'CON-001', employeeId: 'EMP-001', employeeName: 'John Doe', startDate: '2023-03-15', wage: 6500, salaryStructure: 'Standard Full-Time', workingSchedule: 'Standard 40h', status: 'ACTIVE' },
  { id: 'CON-002', employeeId: 'EMP-002', employeeName: 'Maya Lin', startDate: '2022-08-01', wage: 7200, salaryStructure: 'Executive Full-Time', workingSchedule: 'Standard 40h', status: 'ACTIVE' },
  { id: 'CON-003', employeeId: 'EMP-003', employeeName: 'Alex Rivera', startDate: '2024-01-10', wage: 5200, salaryStructure: 'Standard Full-Time', workingSchedule: 'Standard 40h', status: 'ACTIVE' },
];

export const initialPayruns: Payrun[] = [
  {
    id: 'PR-2026-09',
    name: 'September 2026 Regular Cycle',
    period: 'Sep 01 – Sep 30, 2026',
    salaryStructure: 'Standard Full-Time Tech',
    totalGross: 40000,
    totalNet: 33450,
    employeeCount: 6,
    status: 'COMPUTED',
    payslips: [
      { id: 'PS-001', employeeId: 'EMP-001', employeeName: 'John Doe', department: 'Engineering', basic: 4000, hra: 1600, allowance: 900, gross: 6500, tax: 650, otherDeductions: 450, net: 5400, status: 'COMPUTED' },
      { id: 'PS-002', employeeId: 'EMP-002', employeeName: 'Maya Lin', department: 'Product', basic: 4500, hra: 1800, allowance: 900, gross: 7200, tax: 720, otherDeductions: 500, net: 5980, status: 'COMPUTED' },
      { id: 'PS-003', employeeId: 'EMP-003', employeeName: 'Alex Rivera', department: 'Finance', basic: 3200, hra: 1280, allowance: 720, gross: 5200, tax: 520, otherDeductions: 360, net: 4320, status: 'COMPUTED' },
      { id: 'PS-004', employeeId: 'EMP-004', employeeName: 'Elena Rostova', department: 'HR', basic: 5000, hra: 2000, allowance: 1000, gross: 8000, tax: 800, otherDeductions: 560, net: 6640, status: 'COMPUTED' },
      { id: 'PS-005', employeeId: 'EMP-005', employeeName: 'David Kim', department: 'Engineering', basic: 4200, hra: 1680, allowance: 920, gross: 6800, tax: 680, otherDeductions: 470, net: 5650, status: 'COMPUTED' },
      { id: 'PS-006', employeeId: 'EMP-006', employeeName: 'Sarah Connor', department: 'Operations', basic: 3900, hra: 1560, allowance: 840, gross: 6300, tax: 630, otherDeductions: 440, net: 5230, status: 'COMPUTED', warning: '1 Unpaid Absence day deducted' },
    ],
  },
];
